Controllers/MaintenanceController.cs
using Microsoft.AspNetCore.Mvc;

namespace TimeBasedPreventiveMeasures.Controllers
{
    public class MaintenanceController : Controller
    {
        public IActionResult Index()
        {
            return RedirectToAction("History");
        }

        public IActionResult History()
        {
            return View();
        }
    }
}

Controllers/ProductController.cs
using Azure.Core;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using System.Reflection.Metadata.Ecma335;
using TimeBasedPreventiveMeasures.Data;
using TimeBasedPreventiveMeasures.Models.Data;
using TimeBasedPreventiveMeasures.Models.ViewModel;
using TimeBasedPreventiveMeasures.Services;

namespace TimeBasedPreventiveMeasures.Controllers
{
	public class ProductController : Controller
	{
		private readonly LifecycleManagementDB _context;
		private readonly INotificationService _notificationService;
		private IEnumerable<Product> _products = new List<Product>();
		private IEnumerable<Custodian> _custodians = new List<Custodian>();

		public ProductController(LifecycleManagementDB lifecycleManagementDB, INotificationService notificationService)
		{
			_context = lifecycleManagementDB;
			_notificationService = notificationService;
		}

		#region ViewResults
		public async Task<IActionResult> Index(string searchString)
		{
			IEnumerable<Product> _products = 
				await _context.Products
					.Include(c => c.AssigendItCustodian)
					.ToListAsync();

			// Search functionality
			if (!string.IsNullOrEmpty(searchString))
			{
				_products = _products.Where(e => e.ProductName.Contains(searchString) || e.ProductCode.Contains(searchString));
			}

			return View(_products);
		}

        public async Task<IActionResult> ProductDetails(int id)
        {
            var product = await _context.Products
                .Include(p => p.ActionPlans)
                .ThenInclude(ap => ap.AssignedToCustodian)
                .FirstOrDefaultAsync(m => m.ProductId == id);

			if (product == null)
			{
				return NotFound();
			}

			return View(product);
		}

		[HttpGet]
        public IActionResult AddProduct()
		{
			var viewModel = new ProductViewModel();
			viewModel.IsEditMode = false;

            var custodians = _context.Custodians.ToList();
            ViewBag.Custodians = new SelectList(custodians, "CustodianId", "CustodianRole");

			return View(viewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> AddProduct(ProductViewModel viewModel)
		{
			var test = viewModel;
			if (ModelState.IsValid)
			{
				var product = ProductViewModel.ToDataModel(viewModel);
				_context.Add(product);
				await _context.SaveChangesAsync();
				// Check and send notifications if necessary
				var currentDate = DateTime.UtcNow.Date;
				await _notificationService.GenerateEOSNotificationForProductAsync(product, currentDate);
				await _notificationService.GenerateEOLNotificationForProductAsync(product, currentDate);

				return RedirectToAction("Index");
			}

            var custodians = _context.Custodians.ToList();
            ViewBag.Custodians = new SelectList(custodians, "CustodianId", "CustodianRole");

			return View("Index");
		}

		[HttpGet]
        public async Task<IActionResult> EditProduct(int id)
		{
			var productData = await _context.Products
				.Include(c => c.AssigendItCustodian)
				.FirstOrDefaultAsync(p => p.ProductId == id) ?? new Product { };


			_custodians = _context.Custodians.ToList();

			List<CustodianViewModel> custodians = new List<CustodianViewModel>();
            foreach (var item in _custodians)
            {
                custodians.Add(CustodianViewModel.ToViewModel(item));
            };

			ProductViewModel viewModel = ProductViewModel.ToViewModel(_context.Products.FirstOrDefault(p => p.ProductId == id) ?? new());
            viewModel.AssignedCustodian = CustodianViewModel.ToViewModel(productData.AssigendItCustodian ?? new());

			viewModel.IsEditMode = true;

			return View("AddProduct", viewModel);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> EditProduct(int id, ProductViewModel viewModel)
		{
			if (ModelState.IsValid)
			{
				var productToUpdate = await _context.Products.FirstOrDefaultAsync(p => p.ProductId == id);
				
				if (productToUpdate != null)
				{
					productToUpdate.ProductName = viewModel.ProductName;
					productToUpdate.ProductVersion = viewModel.ProductVersion;
					productToUpdate.ProductCategory = viewModel.ProductCategory;
					productToUpdate.Status = viewModel.Status;
					productToUpdate.Manufacturer = viewModel.Manufacturer;
					productToUpdate.VendorName = viewModel.VendorName;
					productToUpdate.PurchaseOrderNo = viewModel.PurchaseOrderNo;
					productToUpdate.AssignedITCustodianId = viewModel.AssignedITCustodianId;
					productToUpdate.EOSDate = viewModel.EOSDate;
					productToUpdate.EOLDate = viewModel.EOLDate;
					productToUpdate.EOESDate = viewModel.EOESDate;
					productToUpdate.SupportDocumentationURL = viewModel.SupportDocumentationURL;
					productToUpdate.SupportEmail = viewModel.SupportEmail;

                    _context.Products.Update(productToUpdate);
					_context.SaveChanges();
                }

                _products = await _context.Products.ToListAsync();
                var product = await _context.Products
					.Include(p => p.ActionPlans)
					.ThenInclude(ap => ap.AssignedToCustodian)
					.FirstOrDefaultAsync(m => m.ProductId == id);

                return View("ProductDetails", product);
            }

			return NotFound();	
		}

		public IActionResult HardwareHistoryPartial()
		{
			return PartialView("_HardwareMaintenanceHistoryPartial");
		}
		#endregion

		#region RemoteValidation
		/// <summary>
		///     An action for remote validation if the product code is already taken, only if the
		///     form is not in Product Mode. Otherwise the validation will not validate.
		/// </summary>
		/// <param name="productCode">The product code to be checked if already existing</param>
		/// <param name="isEditMode">Determines if the form is in Edit Mode</param>
		/// <returns>
		///     Returns the Json format string for handling validation message if 
		///     the product code already exists and true if the validation is successful
		/// </returns>
		[AcceptVerbs("GET", "POST")]
		public async Task<IActionResult> ValidateProductCodeIfTaken(
			string productCode, bool isEditMode)
		{
            if (!isEditMode)
			{
				bool isTaken = await _context.Products.AnyAsync(p => p.ProductCode == productCode);

				if (isTaken)
				{
					return Json($"Product code {productCode} is already taken");
				}
			}

			return Json(true);
		}
        #endregion

        #region JsonResults
        [HttpGet]
        public JsonResult SearchCustodian(string term)
        {
            string _term = term == null ? "" : term.Trim();

            var custodians = _context.Custodians.ToList()
                .Where(c =>
                    $"{c.FirstName} {c.LastName}".Contains(
                        _term, StringComparison.InvariantCultureIgnoreCase) ||
                    c.CustodianRole.Contains(
                        _term, StringComparison.InvariantCultureIgnoreCase) ||

                    c.Email.Contains(
                        _term, StringComparison.InvariantCultureIgnoreCase))
                .ToList();
            return Json(custodians);
        }
        #endregion
    }

}

Views/Shared/_Layout.cshtml
@{
    string currentScreen = ViewData["CurrentScreen"]?.ToString() ?? "Home";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom_styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom_components.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/product_details_styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TimeBasedPreventiveMeasures.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link href="https://cdn.datatables.net/v/bs5/dt-2.0.8/datatables.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/3.0.2/css/responsive.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/3.0.2/css/responsive.dataTables.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow custom_header fixed-top">
            <div class="container-fluid">

                @*Logo*@
                <p class="h3">Metrobank</p>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                @*Nav*@
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-center">
                    <ul class="nav nav-pills custom_header_navigation mt-2 mb-2 navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link @(currentScreen == "Home" ? "active" : "text-dark")" aria-current="page" href="@Url.Action("Index", "Home")">Overview</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @(currentScreen == "Hardwares" ? "active" : "text-dark")" href="@Url.Action("Index", "Product")">Inventory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link @(currentScreen == "History" ? "active" : "text-dark")" href="@Url.Action("History", "Maintenance")">History</a>
                        </li>
                    </ul>
                </div>

                <div id="notif-container" class="notification-popup me-2 border" style="position: absolute; right: 0; top: 0; margin-top: 64px">
                </div>

                <a id="notif-btn" class="btn notification-button">
                    <i class="bi bi-bell-fill"></i>
                </a>
            </div>
        </nav>
    </header>
    <br/>
    <main role="main" class="p-4 mt-5">
        @RenderBody()
    </main>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TimeBasedPreventiveMeasures - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>

    <script src="https://cdn.datatables.net/v/bs5/dt-2.0.8/datatables.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/3.0.2/js/dataTables.responsive.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.2/js/dataTables.buttons.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

    <script src="~/jquery-ui/dist/jquery-ui.js"></script>



</body>
</html>