Models/Data/Notification.cs
using Microsoft.AspNetCore.Mvc;

namespace TimeBasedPreventiveMeasures.Models
{
	public class Notification
	{
		public int NotificationId { get; set; }
		public string? Subject { get; set; }
		public string? Message { get; set; }
		public int? ITCustodianId { get; set; }
		public string? PurchaseOrderNo { get; set; }
		public DateTime CreatedAt { get; set; }
		public bool IsRead { get; set; }
	}
}

Controllers/NotificationController.cs
using Microsoft.AspNetCore.Mvc;

namespace TimeBasedPreventiveMeasures.Controllers
{
    public class NotificationController : Controller
    {
        public IActionResult Index()
        {
            //Example change
            return View();
        }

        public IActionResult NotificationListPartial(bool isPartial = true)
        {
            ViewData["IsPartial"] = isPartial;
            return PartialView("_NotificationListPartial");
        }
    }
}

Views/Notification/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Notifications";
    ViewData["CurrentScreen"] = "Notifications";
}

<div class="d-flex mb-4">
    <p class="h3 mb-0 align-middle">
        <a id="back-btn" class="bi h3 bi-arrow-left-short me-2"></a>
        All Notifications
    </p>
</div>

<div class="form-section-medium form-section-shadow justify-content-center m-auto card border-0 p-4">
    <div id="notifications-placeholder">

    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            sendAjaxRequest(
                `${baseUrl}/Notification/NotificationListPartial?isPartial=false`,
                'GET',
                {},
                (data) => {
                    document.getElementById('notifications-placeholder').innerHTML = data
                },
                (data) => {
                    alert(baseUrl)
                }
            );
        });
    </script>
}

Views/Notification/_NotificationListPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    bool isPartial = (bool)(ViewData["IsPartial"] ?? false);
}

<div class="d-flex flex-column">
    <div class="d-flex align-items-center mb-4">
        <p class="h5 flex-fill mb-0">Notifications</p>

        @*Only show if showAll is true*@
        @if (!isPartial)
        {
            <input type="email" class="form-control w-auto me-2" id="exampleFormControlInput1" placeholder="Search">
            <a class="btn btn-light custom border"><i class="bi bi-check-all me-2"></i>Mark all as read</a>

        }

        @if (isPartial)
        {
            <a class="btn btn-light custom border me-2"><i class="bi bi-check-all"></i></a>
            <a class="btn btn-light custom-button-light" asp-action="Index" asp-controller="Notification">View all</a>
        }
    </div>

    @for (int i = 0; i < 25; i++)
    {
        <div class=" p-2 border-0 border-top pointer notification-item" onclick="viewNotification()">
            <div class="d-flex flex-column">
                <div class="d-flex align-items-center">
                    @*Prefix*@
                    <div class="status-badge-dot status-critical me-2"></div>
                    @*Main Content*@
                    <div class="d-flex flex-column">
                        <p class="mb-0 flex-fill"><span class="h6">[Hardware Name]</span> license is expiring in 24 days.</p>
                        <p class="mb-0">[Notification short description here or message]</p>
                    </div>

                    @*Suffix*@
                </div>

                <div class="d-flex small text-secondary">
                    July 24, 2024
                </div>
            </div>
        </div>
    }
</div>