Models/Data/Custodian.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TimeBasedPreventiveMeasures.Models.Data
{
    public class Custodian
    {
        [Key]
        public int CustodianId { get; set; }

        [Column(TypeName = "NVARCHAR(250)")]
        [DisplayName("First Name")]
        [Required(ErrorMessage = "This field is required.")]
        public string FirstName { get; set; }

        [Column(TypeName = "NVARCHAR(250)")]
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "This field is required.")]
        public string LastName { get; set; }

        [Column(TypeName = "NVARCHAR(250)")]
        [DisplayName("Role")]
        [Required(ErrorMessage = "This field is required.")]
        public string CustodianRole { get; set; }

        [Column(TypeName = "NVARCHAR(100)")]
        [DisplayName("Email")]
        [Required(ErrorMessage = "This field is required.")]
        public string Email { get; set; }

        public IEnumerable<Product>? Products { get; set; }
    }
}

Controllers/CustodianController.cs
#nullable disable
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TimeBasedPreventiveMeasures.Data;
using TimeBasedPreventiveMeasures.Models.Data;

namespace TimeBasedPreventiveMeasures.Controllers
{
    public class CustodianController : Controller
    {
        private readonly LifecycleManagementDB _context;

        public CustodianController(LifecycleManagementDB context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string searchString)
        {

            IQueryable<Custodian> custodiansQuery = _context.Custodians;
   
            if (!string.IsNullOrEmpty(searchString))
            {
                
                if (searchString.Contains(" "))
                {
                    // Full name search
                    string firstName = searchString.Substring(0, searchString.IndexOf(" ")).Trim();
                    string lastName = searchString.Substring(searchString.IndexOf(" ") + 1).Trim();

                    custodiansQuery = custodiansQuery.Where(c =>
                        EF.Functions.Like(c.FirstName.ToUpper(), $"%{firstName.ToUpper()}%") &&
                        EF.Functions.Like(c.LastName.ToUpper(), $"%{lastName.ToUpper()}%")
                    );
                }
                else
                {
             
                    string[] searchTerms = searchString.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);

            
                    custodiansQuery = custodiansQuery.Where(c =>
                        searchTerms.Any(term =>
                            EF.Functions.Like(c.FirstName.ToUpper(), $"%{term.ToUpper()}%") ||
                            EF.Functions.Like(c.LastName.ToUpper(), $"%{term.ToUpper()}%") ||
                            EF.Functions.Like(c.CustodianRole.ToUpper(), $"%{term.ToUpper()}%")
                        )
                    );
                }
            }

            List<Custodian> custodians = await custodiansQuery.ToListAsync();

            return View(custodians);
        }

        public IActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
            {

                return View(new Custodian());
            }
            else
            {
                var custodian = _context.Custodians.Find(id);
                if (custodian == null)
                {
                    return NotFound();
                }
                return View(custodian);
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int id, [Bind("CustodianId,FirstName,LastName,CustodianRole,Email")] Custodian custodian)
        {
            if (id != custodian.CustodianId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (custodian.CustodianId == 0)
                    {
                        _context.Add(custodian);
                    }
                    else
                    {
                        _context.Update(custodian);
                    }

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustodianExists(custodian.CustodianId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(custodian);
        }

        private bool CustodianExists(int id)
        {
            return _context.Custodians.Any(e => e.CustodianId == id);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var custodian = await _context.Custodians.FindAsync(id);
            if (custodian == null)
            {
                return NotFound();
            }
            _context.Custodians.Remove(custodian);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> GetAllCustodians()
        {
            var custodians = await _context.Custodians.ToListAsync();
            return Json(custodians);
        }
    }
}

Views/Custodian/AddOrEdit.cshtml
@model TimeBasedPreventiveMeasures.Models.Data.Custodian

@{
    ViewData["Title"] = "Hardwares";
    ViewData["CurrentScreen"] = "Hardwares";
}

<style>
    .AddIT {
        background-color: #E3F1FF;
        max-width: 100%;
        width: 1400px;
        padding: 20px;
        display: flex;
        height: 80vh;
        flex-wrap: wrap;
        justify-content: center;
        overflow: auto;
        gap: 10px;
    }

    .form-group {
        display: flex;
        flex-direction: column;
        justify-content: center; 
    }

    .form-control {
        border-radius: 25px; 
        width: 100%; 
    }

    .form-row {
        width: 100%;
        display: flex;
        justify-content: space-between;
    }

        .form-row .form-group {
            flex: 0 0 48%;
            margin-bottom: 1rem;
        }
    .viewlist{
        justify-content:center;
        background-color: #7895CB;
    }

    .register{
        background-color: #4A55A2;
        border-radius: 25px;
    }

</style>
<div class="container">
    <div class="row">
        <form asp-action="AddOrEdit" autocomplete="off" class="AddIT">
            <div class="d-flex align-items-center mb-3">
                <a id="Itperson" class="btn person-button">
                    <i class="bi bi-person-circle" style="font-size: 5rem;"></i>
                </a>
                <h1>Add IT Custodian
                    <div class="viewbutton center">
                        <a asp-action="Index" class="btn btn-secondary viewlist" style="width: 50%; margin-left: 60px;" >View Lists</a>
                    </div>
                </h1>
            </div>

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CustodianId" />

            <div class="form-row row">
                <div class="form-group col-md-6 col-lg-3 position-relative">
                    <label asp-for="FirstName" class="control-label"></label>
                    <div class="input-group">
                        <input asp-for="FirstName" class="form-control responsive-input" />
                        <div class="input-group-append">
                            <span class="input-group-text icon-wrapper"><i class="bi bi-person-square"></i></span>
                        </div>
                    </div>
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6 col-lg-3 position-relative">
                    <label asp-for="LastName" class="control-label"></label>
                    <div class="input-group">
                        <input asp-for="LastName" class="form-control responsive-input" />
                        <div class="input-group-append">
                            <span class="input-group-text icon-wrapper"><i class="bi bi-person-square"></i></span>
                        </div>
                    </div>
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6 col-lg-3 position-relative">
                    <label asp-for="CustodianRole" class="control-label"></label>
                    <div class="input-group">
                        <input asp-for="CustodianRole" class="form-control responsive-input" />
                        <div class="input-group-append">
                            <span class="input-group-text icon-wrapper"><i class="bi bi-person-add"></i></span>
                        </div>
                    </div>
                    <span asp-validation-for="CustodianRole" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6 col-lg-3 position-relative">
                    <label asp-for="Email" class="control-label"></label>
                    <div class="input-group">
                        <input asp-for="Email" class="form-control responsive-input" />
                        <div class="input-group-append">
                            <span class="input-group-text icon-wrapper"><i class="bi bi-envelope-at-fill"></i></span>
                        </div>
                    </div>
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="row mt-2">
                <div class="col-md-8">
                    <div class="addbutton">
                        <input type="submit" value="Submit" class="btn btn-primary register" style="width:200%; margin-right: 200px; " />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Custodian/Index.cshtml
@model IEnumerable<TimeBasedPreventiveMeasures.Models.Data.Custodian>

@{
    ViewData["Title"] = "Hardwares";
    ViewData["CurrentScreen"] = "Hardwares";
}

<style>
    .header {
        border: 1px solid #ccc;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        background-color: #C5DFF8;
        margin-bottom: 20px;
        overflow: auto;
    }

        .header .ITheader {
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .header h5 {
            margin: 0;
            flex: 1;
        }

            .header h5 input {
                display: inline-block;
                width: auto;
            }

        .header .btn {
            display: flex;
            align-items: center;
            text-decoration: none;
        }

            .header .btn .bi {
                margin-right: 10px;
            }

    #Itperson {
        display: flex;
        align-items: center;
        margin-right: 10px;
    }

        #Itperson h1 {
            font-size: 1.25rem;
            margin: 0;
            text-align: left;
        }

    .add-button {
        width: 8%;
        height: 20%;
        font-size: 20px;
        margin-top: -25px;
        background-color: #4A55A2;
        justify-content: center;
        border-radius: 15px;
    }

    .table-container {
        max-width: 200%;
    }

    .table th, .table td {
        text-align: left;
        padding: 8px;
    }

    .table thead th {
        background-color: #4A55A2;
        color: #fff;
    }

    .table tbody tr {
        background-color: #C5DFF8;
    }

        .table tbody tr:nth-child(even) {
            background-color: #d1ecf1;
        }

    .table th:nth-child(1), .table td:nth-child(1) {
        width: 25%;
    }

    .table th:nth-child(2), .table td:nth-child(2) {
        width: 25%;
    }

    .table th:nth-child(3), .table td:nth-child(3) {
        width: 20%;
    }

    .table th:nth-child(4), .table td:nth-child(4) {
        width: 20%;
    }

</style>

<div class="header">
    <div class="row ITheader">
        <h5>
            Search for It Custodians
            <form class="d-flex" asp-action="Index" asp-controller="Custodian">
                <input id="custom-search-box" name="searchString" class="form-control me-1" type="search" placeholder="Search" aria-label="Search" value="@ViewData["CurrentFilter"]">
            </form>
            <i>
                <h3 style="margin-left: 570px; margin-top: -50px"> IT Custodians Lists</h3>
            </i>
        </h5>
        <a asp-action="AddOrEdit" class="btn btn-sm btn-success add-button" style="margin-top: 10px; margin-right: 50px;">
            <i class="bi bi-plus-circle-fill" style="margin-right: 1px; color:white;"></i> Add
        </a>
    </div>
</div>

<div class="row">
    <div class="col table-container">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.LastName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CustodianRole)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>
                    <th>
                        <h5 style="font-size: 15px;">Update</h5>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <i class="bi bi-person-badge-fill"></i>
                            @Html.DisplayFor(modelItem => item.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CustodianRole)
                        </td>
                        <td>
                            <i class="bi bi-envelope-check-fill"></i>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            <form asp-action="Delete" asp-route-id="@item.CustodianId">
                                <div class="btn-group btn-group-sm">
                                    <a asp-action="AddOrEdit" asp-route-id="@item.CustodianId" class="btn btn-warning">
                                        <i class="fa-solid fa-pen-to-square"></i>
                                    </a>
                                    <button type="submit" class="btn btn-danger"
                                            onclick="return confirm('Are you sure to delete this record?')">
                                        <i class="far fa-trash-alt"></i>
                                    </button>
                                </div>
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>